permalink: /blog/:categories/:title

paginate: 5
paginate_path: /blog/:num

markdown: kramdown

kramdown:
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_css: class
    coderay_line_numbers: table
